engines:
  pmd:
    enabled: true
  structure:
    enabled: false
    channel: java
  duplication:
    enabled: false
    channel: java
    config:
      languages:
        - java
exclude_paths:
  - "**.js"
  - "**.jsx"
  - "**.rb"
  - "**.py"
